# Site settings
title: openQA, automated testing for operating systems
email: openqa@suse.de
description: "Home of openQA, the engine at the heart of http://openqa.opensuse.org"
url: "http://open.qa"

# Build settings
markdown: kramdown
permalink: pretty
