---
name: 'Commit message check'

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      accessToken:
        required: true

jobs:
  base-check-commit-message:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Check subject beginning
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^([A-Z]|\S+:|git subrepo pull)'
          flags: 'g'
          error: 'The subject does not start with a capital or tag.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.accessToken }}

      - name: Check subject line length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{1,72}(\n|$)'
          flags: 'g'
          error: 'The maximum subject line length of 72 characters is exceeded.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.accessToken }}

      - name: Check subject ending
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.+(?<!\.)(\n|$)'
          flags: 'g'
          error: 'The subject cannot not end with a dot.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.accessToken }}

      - name: Check empty line
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.*(\n\n|$)'
          flags: 'g'
          error: 'No newline between title and description.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.accessToken }}
