{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "openqa.fullname" . }}-gateway
  labels:
    {{- include "openqa.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      port: {{ .Values.gateway.port }}
      protocol: HTTP
      {{- if .Values.baseUrl }}
      hostname: {{ .Values.baseUrl | quote }}
      {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "openqa.fullname" . }}-route
  labels:
    {{- include "openqa.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "openqa.fullname" . }}-gateway
  {{- if .Values.baseUrl }}
  hostnames:
    - {{ .Values.baseUrl | quote }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "openqa.fullname" . }}
          port: 80
{{- end }}
