# See https://github.com/helm/chart-testing#configuration
# With Gateway API CRD disabled for chart-testing
chart-dirs:
  - .
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
validate-maintainers: false
